# Generated by Django 4.2.5 on 2023-10-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaper',
            name='topic',
        ),
        migrations.AddField(
            model_name='newspaper',
            name='topics',
            field=models.ManyToManyField(related_name='newspapers', to='agency.topic'),
        ),
    ]
